name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: curl ipinfo.io
    - name: pro
      run: nproc
    - name: memory
      run: free -h
    - name: disk space
      run: df -h
    - name: pwd
      run: pwd
    - name: time
      run: uptime
  
